### ISSUE TITLE
3.96.1 version quotes timbre logging

### ISSUE THREAD

**Issue by zmedelis** [taoensso/encore#73]
From `3.88.0` -> `3.96.1` change causes Timbre logging to appear with quotes

On `3.88.0` it is good 
```
11:11:54 INFO [bosquet.llm.generator:158]: resolver: (template) => :q1
11:11:55 INFO [bosquet.utils: 87]:         💬 Calling http://localhost:11434/api/chat with:
```

On `3.96.1` this turns into quoted strings
```
"11:14:29 INFO [bosquet.llm.generator:158]: resolver: (template) => :q1"
"11:14:29 INFO [bosquet.utils: 87]:         💬 Calling http://localhost:11434/api/chat with:"
```

Tried removing all sorts of dependencies (notably those bringing in log4j, slf4j deps) - does not have an impact. I also have Timbre `log-output-fn` customization. Removed that - still the same result.

My deps.edn if that helps
https://github.com/zmedelis/bosquet/blob/main/deps.edn

**Comment by ptaoussanis** [comment]
@zmedelis Hi Žygimantas, thanks for reporting this - I'm really sorry about the trouble! I've just pushed v3.97.0 to Clojars which reverts the problematic change.

**Comment by zmedelis** [comment]
Amazing! All good now, thanks for the fix.
